let g:mapleader="\<Space>"
set nohlsearch
set hidden
set number
set relativenumber
set scrolloff=3
set expandtab
set tabstop=4
set shiftwidth=4
set smarttab
set autoindent
set smartindent
set encoding=utf-8
set clipboard=unnamedplus
set laststatus=2
set noshowmode
set splitright
set splitbelow
