vim.g.mapleader = ' '
vim.opt.completeopt = { "menu", "menuone", "noselect" } -- For nvim-cmp
vim.opt.hlsearch = false
vim.opt.hidden = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 3
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smarttab = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.encoding = 'utf-8'
vim.opt.clipboard = 'unnamedplus'
vim.opt.laststatus = 2
vim.opt.showmode = false
vim.opt.splitright = true
vim.opt.splitbelow = true
